Repository sistemas-de-informacion/docs, pull requests merged in 2023-04, with the labels that each got.

#305 IFMS Papúa Nueva Guinea, Oracle y el Gobierno de Sudáfrica, Unit4 y Ayuntamiento de Edimburgo y Unit4 y el Condado de Surrey - Adrián Arribas Mateo
  fracasar-con-erp.md
Labels: enhancement

#311 Actividad 2 - Correccion
  fracasar-con-erp.md
Labels: enhancement

#312 Juan Mediano -> Link updated
  fracasar-con-erp.md
Labels: enhancement

#313 Actividad 2 - 2
  fracasar-con-erp.md
Labels: enhancement

#314 2 new failures. Updating document fracasar-con-erp.md
  fracasar-con-erp.md
Labels: enhancement

#316 Juliana Zordan NY post hacked
  insider-threat.md
Labels: enhancement

#323 Insider Threat - Exposición Credenciales Microsoft
  insider-threat.md
Labels: enhancement

#326 Insider Threat-David Arruga 816058
  insider-threat.md
Labels: enhancement

#329 Update insider threat chinese spy in Huawei in Poland
  insider-threat.md
Labels: enhancement

#330 Update insider-threat.md - Álvaro Andrada
  insider-threat.md
Labels: can be improved

#319 Janfranco
  insider-threat.md
Labels: invalid

#321 Insider threat - Sergio Berges
  insider-threat.md
Labels: can be improved

#338 Actividad 4 - Cristina Marzo
  insider-threat.md
Labels: enhancement

#340 Incluido caso Proofpoint vs Abnormal Security, 2021
  insider-threat.md
Labels: enhancement
